[package]
name = "circuit_prover_v2"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zksync_prover_job_processor.workspace = true
zksync_circuit_prover_service.workspace = true

clap.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["macros", "time"] }

#async-trait.workspace = true
#anyhow.workspace = true
#futures.workspace = true
#tokio.workspace = true
#tokio-stream.workspace = true